version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - "./db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"